package Service;

import Cuisine;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jordan
 */


public class CuisineGUI extends javax.swing.JFrame {

    /**
     * Creates new form Cuisine
     */
    public CuisineGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTableName1 = new javax.swing.JLabel();
        lblTableName2 = new javax.swing.JLabel();
        lblTableName3 = new javax.swing.JLabel();
        lblTableName4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCommande11 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCommande21 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCommande31 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCommande41 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtCommande42 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCommande32 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtCommande43 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtCommande33 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtCommande12 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtCommande13 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtCommande23 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtCommande22 = new javax.swing.JTextArea();
        cmdValider4 = new javax.swing.JButton();
        cmdValider3 = new javax.swing.JButton();
        cmdValider1 = new javax.swing.JButton();
        cmdValider2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(327, 92));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {200, 200, 200, 200};
        layout.rowHeights = new int[] {50, 200, 200, 200, 50};
        getContentPane().setLayout(layout);

        lblTableName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTableName1.setText("TableName1");
        getContentPane().add(lblTableName1, new java.awt.GridBagConstraints());

        lblTableName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTableName2.setText("TableName2");
        getContentPane().add(lblTableName2, new java.awt.GridBagConstraints());

        lblTableName3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTableName3.setText("TableName3");
        getContentPane().add(lblTableName3, new java.awt.GridBagConstraints());

        lblTableName4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTableName4.setText("TableName4");
        getContentPane().add(lblTableName4, new java.awt.GridBagConstraints());

        txtCommande11.setColumns(20);
        txtCommande11.setRows(5);
        txtCommande11.setEnabled(false);
        jScrollPane1.setViewportView(txtCommande11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        txtCommande21.setColumns(20);
        txtCommande21.setRows(5);
        txtCommande21.setEnabled(false);
        jScrollPane2.setViewportView(txtCommande21);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        txtCommande31.setColumns(20);
        txtCommande31.setRows(5);
        txtCommande31.setEnabled(false);
        jScrollPane3.setViewportView(txtCommande31);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane3, gridBagConstraints);

        txtCommande41.setColumns(20);
        txtCommande41.setRows(5);
        txtCommande41.setEnabled(false);
        jScrollPane4.setViewportView(txtCommande41);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane4, gridBagConstraints);

        txtCommande42.setColumns(20);
        txtCommande42.setRows(5);
        txtCommande42.setEnabled(false);
        jScrollPane5.setViewportView(txtCommande42);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane5, gridBagConstraints);

        txtCommande32.setColumns(20);
        txtCommande32.setRows(5);
        txtCommande32.setEnabled(false);
        jScrollPane6.setViewportView(txtCommande32);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane6, gridBagConstraints);

        txtCommande43.setColumns(20);
        txtCommande43.setRows(5);
        txtCommande43.setEnabled(false);
        jScrollPane7.setViewportView(txtCommande43);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane7, gridBagConstraints);

        txtCommande33.setColumns(20);
        txtCommande33.setRows(5);
        txtCommande33.setEnabled(false);
        jScrollPane8.setViewportView(txtCommande33);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane8, gridBagConstraints);

        txtCommande12.setColumns(20);
        txtCommande12.setRows(5);
        txtCommande12.setEnabled(false);
        jScrollPane9.setViewportView(txtCommande12);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane9, gridBagConstraints);

        txtCommande13.setColumns(20);
        txtCommande13.setRows(5);
        txtCommande13.setEnabled(false);
        jScrollPane10.setViewportView(txtCommande13);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane10, gridBagConstraints);

        txtCommande23.setColumns(20);
        txtCommande23.setRows(5);
        txtCommande23.setEnabled(false);
        jScrollPane11.setViewportView(txtCommande23);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane11, gridBagConstraints);

        txtCommande22.setColumns(20);
        txtCommande22.setRows(5);
        txtCommande22.setEnabled(false);
        jScrollPane12.setViewportView(txtCommande22);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane12, gridBagConstraints);

        cmdValider4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdValider4.setText("Valider");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(cmdValider4, gridBagConstraints);

        cmdValider3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdValider3.setText("Valider");
        cmdValider3.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(cmdValider3, gridBagConstraints);

        cmdValider1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdValider1.setText("Valider");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(cmdValider1, gridBagConstraints);

        cmdValider2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdValider2.setText("Valider");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(cmdValider2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuisine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdValider1;
    private javax.swing.JButton cmdValider2;
    private javax.swing.JButton cmdValider3;
    private javax.swing.JButton cmdValider4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblTableName1;
    private javax.swing.JLabel lblTableName2;
    private javax.swing.JLabel lblTableName3;
    private javax.swing.JLabel lblTableName4;
    private javax.swing.JTextArea txtCommande11;
    private javax.swing.JTextArea txtCommande12;
    private javax.swing.JTextArea txtCommande13;
    private javax.swing.JTextArea txtCommande21;
    private javax.swing.JTextArea txtCommande22;
    private javax.swing.JTextArea txtCommande23;
    private javax.swing.JTextArea txtCommande31;
    private javax.swing.JTextArea txtCommande32;
    private javax.swing.JTextArea txtCommande33;
    private javax.swing.JTextArea txtCommande41;
    private javax.swing.JTextArea txtCommande42;
    private javax.swing.JTextArea txtCommande43;
    // End of variables declaration//GEN-END:variables
}
