                                                                     
                                                                     
                                                                     
                                             
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jordan
 */

package Service;

import java.awt.*;

public class Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdTable2 = new javax.swing.JButton();
        cmdTable4 = new javax.swing.JButton();
        cmdTable1 = new javax.swing.JButton();
        cmdTable3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 830));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cmdTable2.setText("Table 2");
        cmdTable2.setMaximumSize(new java.awt.Dimension(100, 100));
        cmdTable2.setMinimumSize(new java.awt.Dimension(100, 100));
        cmdTable2.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(cmdTable2);
        cmdTable2.setBounds(610, 460, 100, 100);

        cmdTable4.setText("Table 4");
        cmdTable4.setMaximumSize(new java.awt.Dimension(100, 100));
        cmdTable4.setMinimumSize(new java.awt.Dimension(100, 100));
        cmdTable4.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(cmdTable4);
        cmdTable4.setBounds(610, 620, 100, 100);

        cmdTable1.setText("Table 1");
        cmdTable1.setMaximumSize(new java.awt.Dimension(100, 100));
        cmdTable1.setMinimumSize(new java.awt.Dimension(100, 100));
        cmdTable1.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(cmdTable1);
        cmdTable1.setBounds(430, 460, 100, 100);

        cmdTable3.setText("Table 3");
        cmdTable3.setMaximumSize(new java.awt.Dimension(100, 100));
        cmdTable3.setMinimumSize(new java.awt.Dimension(100, 100));
        cmdTable3.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(cmdTable3);
        cmdTable3.setBounds(430, 620, 100, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Légende");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 250, 100, 40);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Occupé");
        jLabel3.setToolTipText("");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 310, 80, 80);

        jLabel4.setBackground(new java.awt.Color(0, 255, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Libre");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 410, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void setColor(){
        
        //Code qui va chercher les disponibiliés des 4 tables dans SQL
        //et affiche la couleur en conséquence.
        cmdTable1.setBackground(Color.GREEN);
        cmdTable2.setBackground(Color.RED);
        
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setColor();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdTable1;
    private javax.swing.JButton cmdTable2;
    private javax.swing.JButton cmdTable3;
    private javax.swing.JButton cmdTable4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
